import {useEffect,useRef,useState} from 'react';
import type {AppSettings,BuildPlan,Champion,ClientSnapshot,FlashTrackerSnapshot,Role,StatsSnapshot} from './shared/types';
import {rateMatches,recommend} from './core/analysis';

const roles:Record<Role,string>={top:'上单',jungle:'打野',mid:'中单',adc:'下路',support:'辅助'};
const roleIcons:Record<Role,string>={top:'◩',jungle:'♧',mid:'◇',adc:'⌁',support:'♜'};
const tabs=[['draft','英雄推荐','◇'],['tiers','英雄榜单','▤'],['team','队友状态','♧'],['settings','连接设置','⚙']] as const;
type Tab=typeof tabs[number][0];
const emptyClient:ClientSnapshot={connected:false,phase:'未连接',message:'正在寻找本机 LOL 客户端…',enemies:[],allies:[],banned:[],picked:[],teammates:[],updatedAt:''};
const emptyFlash:FlashTrackerSnapshot={enemies:[],timers:[],message:'进入游戏后读取敌方英雄',updatedAt:''};
const phaseNames:Record<string,string>={None:'客户端就绪',Lobby:'组队大厅',Matchmaking:'正在匹配',ReadyCheck:'等待确认',ChampSelect:'英雄选择',InProgress:'游戏进行中',EndOfGame:'对局结束',Reconnect:'等待重连'};
const fmt=(n:number|null|undefined,d=1)=>n==null?'—':n.toFixed(d);
function Portrait({champion,size='normal'}:{champion?:Champion;size?:string}){return <div className={`portrait ${size}`}>{champion?<img key={champion.image} src={champion.image} alt={champion.name} onError={e=>{e.currentTarget.style.display='none';}}/>:<span>?</span>}</div>;}
function ChampionPicker({value,onChange,champions,label}:{value:number;onChange:(n:number)=>void;champions:Champion[];label:string}){
 const [query,setQuery]=useState('');const [open,setOpen]=useState(false);const selected=champions.find(c=>c.id===value);
 return <div className="picker"><button className={`pick-button ${value?'selected':''}`} aria-label={label} onClick={()=>setOpen(!open)}><Portrait champion={selected}/><b>{selected?.name??'选择英雄'}</b><span className="subtle">{selected?.title??'点击添加敌方英雄'}</span></button>{open&&<div className="pick-menu"><input autoFocus placeholder="搜索名称 / 称号 / 英文" value={query} onChange={e=>setQuery(e.target.value)}/><button onClick={()=>{onChange(0);setOpen(false);}}>清除选择</button><div className="pick-results">{champions.filter(c=>`${c.name} ${c.title} ${c.key}`.toLowerCase().includes(query.toLowerCase())).map(c=><button key={c.id} onClick={()=>{onChange(c.id);setOpen(false);setQuery('');}}><Portrait champion={c} size="small"/>{c.name}</button>)}</div></div>}</div>;
}
export default function App(){
 const [tab,setTab]=useState<Tab>('draft');const [role,setRole]=useState<Role>('top');const [champions,setChampions]=useState<Champion[]>([]);
 const [client,setClient]=useState<ClientSnapshot>(emptyClient);const [stats,setStats]=useState<StatsSnapshot|null>(null);const [loading,setLoading]=useState(false);const [error,setError]=useState('');const [catalogError,setCatalogError]=useState('');
 const [enemies,setEnemies]=useState<number[]>([0,0,0,0,0]);const [opponentIndex,setOpponentIndex]=useState(0);const [auto,setAuto]=useState(true);const [includeAllies,setIncludeAllies]=useState(false);const [search,setSearch]=useState('');
 const [appSettings,setAppSettings]=useState<AppSettings>({autoMinimize:true,autoRestore:true,leaguePath:'',ratingHotkey:'F6'});const [plans,setPlans]=useState<BuildPlan[]>([]);const [planLoading,setPlanLoading]=useState(false);const [applyMessage,setApplyMessage]=useState('');const [applying,setApplying]=useState('');const [teamMessage,setTeamMessage]=useState('');const [flash,setFlash]=useState<FlashTrackerSnapshot>(emptyFlash);
 const statsRequest=useRef(0);const refreshing=useRef(false);const firstStats=useRef(true);const autoRef=useRef(auto);autoRef.current=auto;
 const api=window.assistant;const opponentId=enemies[opponentIndex]||undefined;
 const champ=(id:number)=>champions.find(c=>c.id===id);
 async function refreshClient(){if(!api||refreshing.current)return;refreshing.current=true;try{const next=await api.client();setClient(next);if(autoRef.current){setEnemies([...next.enemies.slice(0,5),0,0,0,0,0].slice(0,5));if(next.role)setRole(next.role);}}catch(e){setClient({...emptyClient,message:String(e)});}finally{refreshing.current=false;}}
 async function loadStats(force=false){if(!api)return;const request=++statsRequest.current;setLoading(true);setError('');setStats(null);try{const s=await api.stats(role,opponentId,force);if(request===statsRequest.current)setStats(s);}catch(e){if(request===statsRequest.current)setError(String(e));}finally{if(request===statsRequest.current)setLoading(false);}}
 async function loadChampions(){if(!api)return;setCatalogError('');try{setChampions(await api.champions());}catch(e){setCatalogError(`英雄资料暂不可用：${String(e)}`);}}
 async function updateSettings(next:AppSettings){try{setError('');setAppSettings(await api.saveSettings(next));}catch(e){setError(`保存设置失败：${String(e)}`);void api.settings().then(setAppSettings);}}
 async function apply(plan:BuildPlan){setApplying(plan.id);setApplyMessage('');try{const result=await api.applyPlan(plan);setApplyMessage([result.rune.message,result.items.message,result.spells.message].join('；'));}catch(e){setApplyMessage(String(e));}finally{setApplying('');}}
 async function copyRating(){setTeamMessage('');try{const text=await api.copyTeamRating();setTeamMessage(`已复制：${text}`);}catch(e){setTeamMessage(`复制失败：${String(e)}`);}}
 async function recordEnemyFlash(slot:number){try{setFlash(await api.recordFlash(slot));}catch(e){setTeamMessage(`记录失败：${String(e)}`);}}
 useEffect(()=>{if(!api){setError('请运行桌面程序使用本机数据连接。');return;}void loadChampions();void refreshClient();void api.settings().then(setAppSettings);const timer=setInterval(()=>void refreshClient(),3000);return()=>clearInterval(timer);},[]);
 useEffect(()=>{if(!api)return;const refresh=()=>void api.flashTracker().then(setFlash);refresh();const timer=setInterval(refresh,1000);return()=>clearInterval(timer);},[]);
 useEffect(()=>{const force=firstStats.current&&!opponentId;firstStats.current=false;void loadStats(force);return()=>{statsRequest.current++;};},[role,opponentId]);
 useEffect(()=>{const id=client.rankedDraft&&client.phase==='ChampSelect'?client.ownChampionId:undefined;if(!id||!client.role){setPlans([]);return;}let live=true;setPlanLoading(true);setApplyMessage('');void api.buildPlans(id,client.role).then(value=>{if(live)setPlans(value);}).catch(e=>{if(live)setApplyMessage(`方案获取失败：${String(e)}`);}).finally(()=>{if(live)setPlanLoading(false);});return()=>{live=false;};},[client.rankedDraft,client.phase,client.ownChampionId,client.role]);
 const recommendations=stats?recommend(role,enemies.filter(Boolean),opponentId,[...client.banned,...client.picked],stats,champions,client.allies,includeAllies):[];
 const tierRows=(stats?.rows??[]).filter(r=>r.role===role&&`${champ(r.championId)?.name??''}${champ(r.championId)?.key??''}`.toLowerCase().includes(search.toLowerCase())).sort((a,b)=>(a.tier??9)-(b.tier??9)||b.winRate-a.winRate);
 const source=()=>api?.openSource(stats?.source?.startsWith('https://op.gg/')?stats.source:'https://op.gg/lol/champions');
 const title=tab==='draft'?'让每一次选人，都有依据。':tab==='tiers'?'版本强势，一目了然。':tab==='team'?'先看近况，再做判断。':'准备好，连接峡谷。';
 const subtitle=tab==='draft'?'从分路强度到对位关系，为你的下一手找到更多可能。':tab==='tiers'?'浏览分路榜单，了解版本趋势与英雄强度。':tab==='team'?'最近五场表现速览。一次状态，不定义一位玩家。':'管理客户端连接，了解数据来源与分析方式。';
 return <div className="shell"><aside className="sidebar"><div className="brand"><div className="brand-mark">R</div><div>RIFT<span>COMPANION</span></div></div><div className="workspace-label">你的峡谷工作台</div><nav>{tabs.map(([id,name,icon])=><button aria-label={name} className={tab===id?'active':''} onClick={()=>setTab(id)} key={id}><span>{icon}</span>{name}{tab===id&&<i/>}</button>)}</nav><div className="sidebar-bottom"><span className="eyebrow">CN EDITION</span><p>更从容地进入下一局。</p><div className="version">国服桌面助手 <span>v0.4.0</span></div></div></aside>
 <main><header className="topbar"><span>工作台 <span className="slash">/</span> {tabs.find(x=>x[0]===tab)?.[1]}</span><div className="topbar-actions"><div className="connection"><i className={client.connected?'online':''}/>{client.connected?(phaseNames[client.phase]??client.phase):'客户端未连接'}<span className="divider"/>{client.selfName??'本地模式'}</div><button className="minimize-button" title="最小化" aria-label="最小化程序" onClick={()=>void api.minimize()}>─</button></div></header><div className="content"><div className="page-heading"><div><div className="eyebrow">{tab==='draft'?'DRAFT WITH CONFIDENCE':tab==='tiers'?'THE META, AT A GLANCE':tab==='team'?'YOUR TEAM, RECENT FORM':'CONNECTED TO THE RIFT'}</div><h1>{title}</h1><p>{subtitle}</p></div><button className="outline" onClick={()=>{void refreshClient();void loadStats(true);}}>↻ 刷新数据</button></div>
 {catalogError&&<div className="notice warning">{catalogError}<button onClick={()=>void loadChampions()}>重试</button></div>}
 {(tab==='draft'||tab==='tiers')&&<><div className="filterbar"><div className="role-tabs">{(Object.keys(roles) as Role[]).map(r=><button className={role===r?'active':''} key={r} onClick={()=>{setRole(r);setAuto(false);}}><span>{roleIcons[r]}</span>{roles[r]}</button>)}</div><div className="data-filter">{stats?.region??'Global'} <span>·</span> {stats?.rank??'Emerald+'} <span>·</span> {stats?.patch?`版本 ${stats.patch}`:'等待数据'}</div></div></>}
 {tab==='draft'&&<><section className="panel draft-panel"><div className="section-heading"><div><h2>敌方阵容 <span className="count">{enemies.filter(Boolean).length} / 5</span></h2><p>指定主要对位，推荐将优先考虑这位英雄的 counter 关系。</p></div><div className="draft-options"><label className="toggle"><input type="checkbox" checked={includeAllies} onChange={e=>setIncludeAllies(e.target.checked)}/><span/>结合自家英雄阵容推荐</label><label className="toggle"><input type="checkbox" checked={auto} onChange={e=>{setAuto(e.target.checked);autoRef.current=e.target.checked;if(e.target.checked)void refreshClient();}}/><span/>自动同步</label></div></div><div className="enemy-grid">{enemies.map((id,i)=><div key={i} className={`enemy-slot ${opponentIndex===i?'target':''}`}><div className="slot-label">敌方位置 {i+1}<button onClick={()=>setOpponentIndex(i)} className={opponentIndex===i?'target-badge':''}>{opponentIndex===i?'主要对位':'设为对位'}</button></div><ChampionPicker label={`选择敌方英雄 ${i+1}`} value={id} champions={champions} onChange={v=>{setAuto(false);setEnemies(old=>old.map((n,j)=>j===i?v:n===v&&v!==0?0:n));}}/></div>)}</div><div className="panel-foot"><span className="tiny-dot"/> {auto?'自动同步客户端可见阵容；敌方分路需你指定。':'手动选人模式，可随时重新开启自动同步。'}<button onClick={()=>{setAuto(false);setEnemies([0,0,0,0,0]);}}>清空阵容</button></div></section>
 {applyMessage&&<div className="notice">{applyMessage}</div>}<div className="section-heading results-heading"><div><h2>推荐选择 <span className="count">{recommendations.length?`${recommendations.length} 位候选`:'等待数据'}</span></h2><p>{opponentId?`针对 ${champ(opponentId)?.name??opponentId} 的${roles[role]}对位参考`:`选择${roles[role]}英雄，或添加敌方英雄细化推荐`}{includeAllies?'；已加入自家阵容补位因素':''}</p></div><span className="pill">✧ 综合推荐分 · 非预测胜率</span></div>
 <DataState loading={loading} error={error} stats={stats} onSource={source}/>
 {!loading&&recommendations.length>0&&<div className="recommend-grid">{recommendations.slice(0,6).map((r,i)=><article className={`recommend-card ${i===0?'best':''}`} key={r.championId}><div className="card-top"><span className="eyebrow">{i===0?'首选参考':`备选 ${String(i+1).padStart(2,'0')}`}</span><span className="tier">{r.tier===null?'—':`T${r.tier}`}</span></div><div className="champion-hero"><Portrait champion={champ(r.championId)} size="large"/><div><h3>{champ(r.championId)?.name??`英雄 ${r.championId}`}</h3><span>{champ(r.championId)?.title}</span></div></div><div className="metrics"><div><span>推荐分</span><strong>{fmt(r.score)}</strong></div><div><span>对位胜率</span><strong className={r.matchupWinRate!==null&&r.matchupWinRate>50?'mint':''}>{fmt(r.matchupWinRate)}<small>{r.matchupWinRate!==null?'%':''}</small></strong></div></div><div className="reasons">{r.reasons.map(t=><p key={t}><span>↗</span>{t}</p>)}</div></article>)}</div>}
 {client.rankedDraft&&client.phase==='ChampSelect'&&<section className="loadout-section"><div className="section-heading results-heading"><div><h2>当前英雄方案 <span className="count">{client.ownChampionId?champ(client.ownChampionId)?.name:'锁定英雄后显示'}</span></h2><p>每张卡使用对应符文变体，并搭配页面上的 OP.GG 通用出装；选择后才会写入客户端。</p></div></div>{planLoading&&<div className="notice"><span className="spinner"/>正在读取 OP.GG 最新符文与出装…</div>}<div className="plan-grid">{plans.map(plan=><article className="panel plan-card" key={plan.id}><div className="card-top"><span className="eyebrow">{plan.label}</span><span className="tier">{plan.patch}</span></div><h3>{plan.championName} · {roles[plan.role]}</h3><p><b>符文</b> {plan.perkNames.join(' / ')} · {plan.perkIds.join(' · ')}</p><p><b>召唤师技能</b> {plan.summonerSpellNames.join(' + ')}</p><p><b>出门装</b> {plan.starterItemNames.join(' + ')}</p><p><b>核心装</b> {[...plan.bootItemNames,...plan.coreItemNames].join(' → ')}</p><p><b>技能顺序</b> {plan.skillOrder||'以客户端推荐为准'}</p><div className="plan-meta">符文胜率 {fmt(plan.winRate,2)}% · 符文样本 {plan.games?.toLocaleString()??'—'}{plan.stale?' · 缓存数据':''}</div><button className="primary" disabled={Boolean(applying)} onClick={()=>void apply(plan)}>{applying===plan.id?'正在应用…':'应用此方案'}</button></article>)}</div></section>}
 {!loading&&!recommendations.length&&!error&&stats?.rows.length===0&&<Empty title="暂时没有可用的榜单数据" text="可以刷新重试，或打开 OP.GG 查看原始榜单。"/>}
 </>}
 {tab==='tiers'&&<><DataState loading={loading} error={error} stats={stats} onSource={source}/><section className="panel"><div className="section-heading"><h2>{roles[role]}英雄榜单 <span className="count">{tierRows.length}</span></h2><input className="search" placeholder="搜索英雄名称…" value={search} onChange={e=>setSearch(e.target.value)}/></div><table><thead><tr><th>排名</th><th>英雄</th><th>层级</th><th>胜率</th><th>登场率</th><th>样本量</th><th/></tr></thead><tbody>{tierRows.map((r,i)=><tr key={r.championId}><td className="subtle">{String(i+1).padStart(2,'0')}</td><td><div className="table-champ"><Portrait champion={champ(r.championId)} size="small"/><b>{champ(r.championId)?.name??r.championId}</b></div></td><td><span className="tier">{r.tier===null?'—':`T${r.tier}`}</span></td><td className={r.winRate>=50?'mint':''}>{fmt(r.winRate,2)}%</td><td>{fmt(r.pickRate,2)}{r.pickRate===null?'':'%'}</td><td>{r.games?.toLocaleString()??'—'}</td><td><button className="text-button" onClick={()=>{setEnemies([r.championId,0,0,0,0]);setOpponentIndex(0);setAuto(false);setTab('draft');}}>寻找 counter ↗</button></td></tr>)}</tbody></table>{!tierRows.length&&<Empty title={loading?'正在获取榜单…':'没有匹配的英雄'} text="榜单仅展示成功获取的真实统计。"/>}</section></>}
 {tab==='team'&&<><div className="summary-grid"><div className="summary-box"><span>可见队友</span><strong>{client.teammates.length}<small> 位</small></strong></div><div className="summary-box"><span>分析范围</span><strong>最近 5<small> 场</small></strong></div><div className="summary-box"><span>数据状态</span><strong className="status-text">{client.connected?'客户端已连接':'等待连接'}</strong></div></div><div className="notice"><span>ⓘ</span> 仅分析当前可识别的队友；匿名玩家显示不可查询。胜率仅针对展示的近期对局。</div>
 <section className="panel quick-tools"><div><h2>队友评价消息</h2><p>消息包含上等马、中等马、下等马评级及最近几局胜率。也可随时按 {appSettings.ratingHotkey} 复制。</p></div><button className="primary" disabled={!client.teammates.some(p=>!p.anonymous&&p.matches.length>0)} onClick={()=>void copyRating()}>复制队友评价</button></section>
 {teamMessage&&<div className="notice">{teamMessage}</div>}
 <section className="panel flash-tools"><div className="section-heading"><div><h2>敌方闪现计时</h2><p>游戏中按 Ctrl+Alt+1～5，或点击敌方英雄，按 300 秒基础冷却记录。30 秒和 10 秒时会通知并复制提醒文字。</p></div><span className="pill">{flash.message}</span></div><div className="flash-grid">{flash.enemies.length?flash.enemies.map(enemy=>{const timer=flash.timers.find(item=>item.enemySlot===enemy.slot);const left=timer?Math.max(0,Math.ceil((timer.readyAt-Date.now())/1000)):0;return <div className="flash-enemy" key={enemy.slot}><b>{enemy.slot}. {enemy.championName}</b><span>{timer?`${Math.floor(left/60)}:${String(left%60).padStart(2,'0')} 后转好`:`Ctrl+Alt+${enemy.slot}`}</span><button className={timer?'outline':'primary'} onClick={()=>void recordEnemyFlash(enemy.slot)}>{timer?'重新计时':'记录闪现'}</button>{timer&&<button className="text-button" onClick={async()=>setFlash(await api.clearFlash(timer.id))}>取消</button>}</div>}):<p className="body-copy">进入对局后会通过局内公开接口读取敌方五名英雄。</p>}</div></section>
 {client.teammates.length===0?<Empty title={client.connected?'当前没有可读取的队友':'连接客户端后，查看队友近况'} text={client.message} action={<button className="primary" onClick={()=>setTab('settings')}>查看连接设置 →</button>}/>:<div className="team-list">{client.teammates.map(p=>{const rating=rateMatches(p.matches);return <section className="panel teammate" key={p.id}><div className="player-heading"><Portrait champion={champ(p.championId)}/><div><h3>{p.name}</h3><span>{p.role||'分路未知'}</span></div><span className={`rating ${rating.label==='上等马'?'good':rating.label==='下等马'?'bad':''}`}>{p.anonymous?'匿名玩家':rating.label}</span><div className="player-stat">近 {rating.count} 场胜率 <b>{fmt(rating.winRate,0)}{rating.winRate!==null?'%':''}</b></div><div className="player-stat">KDA <b>{fmt(rating.kda,2)}</b></div><div className="player-stat">状态分 <b>{rating.score??'—'}</b></div></div>{p.error&&<div className="notice warning">{p.error}</div>}<div className="match-strip">{p.matches.map(m=><div key={m.id} className={`match ${m.win?'win':'loss'}`}><div className="match-result">{m.win?'胜利':'失败'}<small>{new Date(m.date).toLocaleDateString('zh-CN',{month:'numeric',day:'numeric'})}</small></div><div className="table-champ"><Portrait champion={champ(m.championId)} size="small"/><b>{champ(m.championId)?.name??m.championId}</b></div><strong>{m.kills} / {m.deaths} / {m.assists}</strong><span>{m.queueId===420?'单双排':m.queueId===440?'灵活排位':m.queueId===450?'极地大乱斗':`模式 ${m.queueId}`} · {Math.floor(m.duration/60)} 分钟</span></div>)}</div><details><summary>评分依据与样本说明</summary><p>{rating.explanation}</p></details></section>;})}</div>}</>}
 {tab==='settings'&&<div className="settings-grid"><section className="panel"><div className="section-heading"><h2>客户端连接</h2><span className={`pill ${client.connected?'mint':''}`}>{client.connected?'已连接':'未连接'}</span></div><p className="body-copy">助手会优先从任务管理器中的 LeagueClient 后台进程读取安装路径与当前会话。WeGame 以管理员权限启动客户端时，助手也需要相同权限。</p><div className="setting-row"><span>游戏路径</span><b>{client.leaguePath||appSettings.leaguePath||'等待后台进程自动发现'}</b></div><div className="setting-row"><span>当前状态</span><b>{client.message}</b></div><div className="button-row"><button className="primary" onClick={()=>void refreshClient()}>↻ 重新连接</button>{!client.connected&&<button className="primary" onClick={async()=>{try{await api.restartElevated();}catch(e){setError(`管理员重启失败：${String(e)}`);}}}>以管理员身份重启</button>}<button className="outline" onClick={async()=>{try{const p=await api.chooseLeaguePath();if(p){setAppSettings(old=>({...old,leaguePath:p}));void refreshClient();}}catch(e){setError(String(e));}}}>主动选择游戏路径</button></div>{error&&<p className="warning">{error}</p>}<div className="window-options"><label className="toggle"><input type="checkbox" checked={appSettings.autoMinimize} onChange={e=>void updateSettings({...appSettings,autoMinimize:e.target.checked})}/><span/>进入游戏自动最小化</label><label className="toggle"><input type="checkbox" checked={appSettings.autoRestore} onChange={e=>void updateSettings({...appSettings,autoRestore:e.target.checked})}/><span/>对局结束自动打开</label></div><div className="hotkey-setting"><label htmlFor="rating-hotkey">复制队友评价快捷键</label><input id="rating-hotkey" value={appSettings.ratingHotkey} onChange={e=>setAppSettings({...appSettings,ratingHotkey:e.target.value})}/><button className="outline" onClick={()=>void updateSettings(appSettings)}>保存快捷键</button><span>支持 F1–F12，可搭配 Ctrl、Alt、Shift</span></div></section><section className="panel"><h2>数据与边界</h2><div className="info-block"><h3>OP.GG 英雄统计</h3><p>每次启动都会后台刷新五个分路。网络失败时保留上次缓存并显示获取时间。</p><button className="text-button" onClick={()=>void api.openSource('https://op.gg/lol/champions')}>访问 OP.GG ↗</button></div><div className="info-block"><h3>本机客户端接口 · LCU</h3><p>队友战绩为只读查询。只有你点击方案后，才写入专用符文页、装备方案和召唤师技能。</p></div></section><section className="panel"><h2>近期状态怎么计算？</h2><p className="body-copy">近五场胜率权重 70%，KDA 权重 30%。KDA 以总击杀、助攻和死亡计算，达到 5 时该项满分。</p><div className="grade-row"><span className="rating good">上等马</span><b>70 分及以上</b></div><div className="grade-row"><span className="rating">中等马</span><b>40–69 分</b></div><div className="grade-row"><span className="rating bad">下等马</span><b>40 分以下</b></div><p className="subtle">不足三场不评级；不代表长期实力或官方段位。</p></section><section className="panel"><h2>推荐分怎么计算？</h2><p className="body-copy">综合分路胜率、英雄层级和主要对位胜率；对位样本越少，权重越低。敌方多刺客或后排较多时，附加少量可解释的阵容规则分。</p><p className="body-copy">主要对位胜率指候选英雄对阵目标英雄的对局胜率，不等于单杀率，也不是本局获胜保证。</p><div className="notice">推荐分用于比较候选，不是预测胜率。</div></section></div>}
 <footer><span>RIFT COMPANION <span className="slash">/</span> 为每一场认真准备</span><span>{client.updatedAt?`客户端检查 ${new Date(client.updatedAt).toLocaleTimeString('zh-CN')}`:'本机运行 · 只读数据'}</span></footer></div></main></div>;
}
function Empty({title,text,action}:{title:string;text:string;action?:React.ReactNode}){return <div className="empty"><div className="empty-icon">◇</div><h3>{title}</h3><p>{text}</p>{action}</div>;}
function DataState({loading,error,stats,onSource}:{loading:boolean;error:string;stats:StatsSnapshot|null;onSource:()=>unknown}){return <>{loading&&<div className="notice"><span className="spinner"/>正在获取分路榜单与对位统计…</div>}{error&&<div className="notice warning">{error}</div>}{stats&&<div className={`source-line ${stats.stale||stats.error?'warning':''}`}><span>{stats.error??(stats.stale?'正在显示历史缓存':'真实统计 · OP.GG')}{stats.fetchedAt?` · 获取于 ${new Date(stats.fetchedAt).toLocaleString('zh-CN')}`:''} · 非国服统计参考</span><button onClick={()=>void onSource()}>查看来源 ↗</button></div>}</>;}
