import {useEffect,useRef,useState} from 'react';
import type {Champion,ClientSnapshot,Role,StatsSnapshot} from './shared/types';
import {rateMatches,recommend} from './core/analysis';

const roles:Record<Role,string>={top:'上单',jungle:'打野',mid:'中单',adc:'下路',support:'辅助'};
const roleIcons:Record<Role,string>={top:'◩',jungle:'♧',mid:'◇',adc:'⌁',support:'♜'};
const tabs=[['draft','英雄推荐','◇'],['tiers','英雄榜单','▤'],['team','队友状态','♧'],['settings','连接设置','⚙']] as const;
type Tab=typeof tabs[number][0];
const emptyClient:ClientSnapshot={connected:false,phase:'未连接',message:'正在寻找本机 LOL 客户端…',enemies:[],banned:[],picked:[],teammates:[],updatedAt:''};
const phaseNames:Record<string,string>={None:'客户端就绪',Lobby:'组队大厅',Matchmaking:'正在匹配',ReadyCheck:'等待确认',ChampSelect:'英雄选择',InProgress:'游戏进行中',EndOfGame:'对局结束',Reconnect:'等待重连'};
const fmt=(n:number|null|undefined,d=1)=>n==null?'—':n.toFixed(d);
function Portrait({champion,size='normal'}:{champion?:Champion;size?:string}){return <div className={`portrait ${size}`}>{champion?<img key={champion.image} src={champion.image} alt={champion.name} onError={e=>{e.currentTarget.style.display='none';}}/>:<span>?</span>}</div>;}
function ChampionPicker({value,onChange,champions,label}:{value:number;onChange:(n:number)=>void;champions:Champion[];label:string}){
 const [query,setQuery]=useState('');const [open,setOpen]=useState(false);const selected=champions.find(c=>c.id===value);
 return <div className="picker"><button className={`pick-button ${value?'selected':''}`} aria-label={label} onClick={()=>setOpen(!open)}><Portrait champion={selected}/><b>{selected?.name??'选择英雄'}</b><span className="subtle">{selected?.title??'点击添加敌方英雄'}</span></button>{open&&<div className="pick-menu"><input autoFocus placeholder="搜索名称 / 称号 / 英文" value={query} onChange={e=>setQuery(e.target.value)}/><button onClick={()=>{onChange(0);setOpen(false);}}>清除选择</button><div className="pick-results">{champions.filter(c=>`${c.name} ${c.title} ${c.key}`.toLowerCase().includes(query.toLowerCase())).map(c=><button key={c.id} onClick={()=>{onChange(c.id);setOpen(false);setQuery('');}}><Portrait champion={c} size="small"/>{c.name}</button>)}</div></div>}</div>;
}
export default function App(){
 const [tab,setTab]=useState<Tab>('draft');const [role,setRole]=useState<Role>('top');const [champions,setChampions]=useState<Champion[]>([]);
 const [client,setClient]=useState<ClientSnapshot>(emptyClient);const [stats,setStats]=useState<StatsSnapshot|null>(null);const [loading,setLoading]=useState(false);const [error,setError]=useState('');const [catalogError,setCatalogError]=useState('');
 const [enemies,setEnemies]=useState<number[]>([0,0,0,0,0]);const [opponentIndex,setOpponentIndex]=useState(0);const [auto,setAuto]=useState(true);const [search,setSearch]=useState('');const [lockfile,setLockfile]=useState('自动发现');
 const statsRequest=useRef(0);const refreshing=useRef(false);const autoRef=useRef(auto);autoRef.current=auto;
 const api=window.assistant;const opponentId=enemies[opponentIndex]||undefined;
 const champ=(id:number)=>champions.find(c=>c.id===id);
 async function refreshClient(){if(!api||refreshing.current)return;refreshing.current=true;try{const next=await api.client();setClient(next);if(autoRef.current){setEnemies([...next.enemies.slice(0,5),0,0,0,0,0].slice(0,5));if(next.role)setRole(next.role);}}catch(e){setClient({...emptyClient,message:String(e)});}finally{refreshing.current=false;}}
 async function loadStats(force=false){if(!api)return;const request=++statsRequest.current;setLoading(true);setError('');setStats(null);try{const s=await api.stats(role,opponentId,force);if(request===statsRequest.current)setStats(s);}catch(e){if(request===statsRequest.current)setError(String(e));}finally{if(request===statsRequest.current)setLoading(false);}}
 async function loadChampions(){if(!api)return;setCatalogError('');try{setChampions(await api.champions());}catch(e){setCatalogError(`英雄资料暂不可用：${String(e)}`);}}
 useEffect(()=>{if(!api){setError('请运行桌面程序使用本机数据连接。');return;}void loadChampions();void refreshClient();const timer=setInterval(()=>void refreshClient(),6000);return()=>clearInterval(timer);},[]);
 useEffect(()=>{void loadStats();return()=>{statsRequest.current++;};},[role,opponentId]);
 const recommendations=stats?recommend(role,enemies.filter(Boolean),opponentId,[...client.banned,...client.picked],stats,champions):[];
 const tierRows=(stats?.rows??[]).filter(r=>r.role===role&&`${champ(r.championId)?.name??''}${champ(r.championId)?.key??''}`.toLowerCase().includes(search.toLowerCase())).sort((a,b)=>(a.tier??9)-(b.tier??9)||b.winRate-a.winRate);
 const source=()=>api?.openSource(stats?.source?.startsWith('https://op.gg/')?stats.source:'https://op.gg/lol/champions');
 const title=tab==='draft'?'让每一次选人，都有依据。':tab==='tiers'?'版本强势，一目了然。':tab==='team'?'先看近况，再做判断。':'准备好，连接峡谷。';
 const subtitle=tab==='draft'?'从分路强度到对位关系，为你的下一手找到更多可能。':tab==='tiers'?'浏览分路榜单，了解版本趋势与英雄强度。':tab==='team'?'最近五场表现速览。一次状态，不定义一位玩家。':'管理客户端连接，了解数据来源与分析方式。';
 return <div className="shell"><aside className="sidebar"><div className="brand"><div className="brand-mark">R</div><div>RIFT<span>COMPANION</span></div></div><div className="workspace-label">你的峡谷工作台</div><nav>{tabs.map(([id,name,icon])=><button aria-label={name} className={tab===id?'active':''} onClick={()=>setTab(id)} key={id}><span>{icon}</span>{name}{tab===id&&<i/>}</button>)}</nav><div className="sidebar-bottom"><span className="eyebrow">CN EDITION</span><p>更从容地进入下一局。</p><div className="version">国服桌面助手 <span>v0.1.0</span></div></div></aside>
 <main><header className="topbar"><span>工作台 <span className="slash">/</span> {tabs.find(x=>x[0]===tab)?.[1]}</span><div className="connection"><i className={client.connected?'online':''}/>{client.connected?(phaseNames[client.phase]??client.phase):'客户端未连接'}<span className="divider"/>{client.selfName??'本地模式'}</div></header><div className="content"><div className="page-heading"><div><div className="eyebrow">{tab==='draft'?'DRAFT WITH CONFIDENCE':tab==='tiers'?'THE META, AT A GLANCE':tab==='team'?'YOUR TEAM, RECENT FORM':'CONNECTED TO THE RIFT'}</div><h1>{title}</h1><p>{subtitle}</p></div><button className="outline" onClick={()=>{void refreshClient();void loadStats(true);}}>↻ 刷新数据</button></div>
 {catalogError&&<div className="notice warning">{catalogError}<button onClick={()=>void loadChampions()}>重试</button></div>}
 {(tab==='draft'||tab==='tiers')&&<><div className="filterbar"><div className="role-tabs">{(Object.keys(roles) as Role[]).map(r=><button className={role===r?'active':''} key={r} onClick={()=>{setRole(r);setAuto(false);}}><span>{roleIcons[r]}</span>{roles[r]}</button>)}</div><div className="data-filter">{stats?.region??'Global'} <span>·</span> {stats?.rank??'Emerald+'} <span>·</span> {stats?.patch?`版本 ${stats.patch}`:'等待数据'}</div></div></>}
 {tab==='draft'&&<><section className="panel draft-panel"><div className="section-heading"><div><h2>敌方阵容 <span className="count">{enemies.filter(Boolean).length} / 5</span></h2><p>指定主要对位，推荐将优先考虑这位英雄的 counter 关系。</p></div><label className="toggle"><input type="checkbox" checked={auto} onChange={e=>{setAuto(e.target.checked);autoRef.current=e.target.checked;if(e.target.checked)void refreshClient();}}/><span/>自动同步</label></div><div className="enemy-grid">{enemies.map((id,i)=><div key={i} className={`enemy-slot ${opponentIndex===i?'target':''}`}><div className="slot-label">敌方位置 {i+1}<button onClick={()=>setOpponentIndex(i)} className={opponentIndex===i?'target-badge':''}>{opponentIndex===i?'主要对位':'设为对位'}</button></div><ChampionPicker label={`选择敌方英雄 ${i+1}`} value={id} champions={champions} onChange={v=>{setAuto(false);setEnemies(old=>old.map((n,j)=>j===i?v:n===v&&v!==0?0:n));}}/></div>)}</div><div className="panel-foot"><span className="tiny-dot"/> {auto?'自动同步客户端可见阵容；敌方分路需你指定。':'手动选人模式，可随时重新开启自动同步。'}<button onClick={()=>{setAuto(false);setEnemies([0,0,0,0,0]);}}>清空阵容</button></div></section>
 <div className="section-heading results-heading"><div><h2>推荐选择 <span className="count">{recommendations.length?`${recommendations.length} 位候选`:'等待数据'}</span></h2><p>{opponentId?`针对 ${champ(opponentId)?.name??opponentId} 的${roles[role]}对位参考`:`选择${roles[role]}英雄，或添加敌方英雄细化推荐`}</p></div><span className="pill">✧ 综合推荐分 · 非预测胜率</span></div>
 <DataState loading={loading} error={error} stats={stats} onSource={source}/>
 {!loading&&recommendations.length>0&&<div className="recommend-grid">{recommendations.slice(0,6).map((r,i)=><article className={`recommend-card ${i===0?'best':''}`} key={r.championId}><div className="card-top"><span className="eyebrow">{i===0?'首选参考':`备选 ${String(i+1).padStart(2,'0')}`}</span><span className="tier">{r.tier===null?'—':`T${r.tier}`}</span></div><div className="champion-hero"><Portrait champion={champ(r.championId)} size="large"/><div><h3>{champ(r.championId)?.name??`英雄 ${r.championId}`}</h3><span>{champ(r.championId)?.title}</span></div></div><div className="metrics"><div><span>推荐分</span><strong>{fmt(r.score)}</strong></div><div><span>对位胜率</span><strong className={r.matchupWinRate!==null&&r.matchupWinRate>50?'mint':''}>{fmt(r.matchupWinRate)}<small>{r.matchupWinRate!==null?'%':''}</small></strong></div></div><div className="reasons">{r.reasons.map(t=><p key={t}><span>↗</span>{t}</p>)}</div></article>)}</div>}
 {!loading&&!recommendations.length&&!error&&stats?.rows.length===0&&<Empty title="暂时没有可用的榜单数据" text="可以刷新重试，或打开 OP.GG 查看原始榜单。"/>}
 </>}
 {tab==='tiers'&&<><DataState loading={loading} error={error} stats={stats} onSource={source}/><section className="panel"><div className="section-heading"><h2>{roles[role]}英雄榜单 <span className="count">{tierRows.length}</span></h2><input className="search" placeholder="搜索英雄名称…" value={search} onChange={e=>setSearch(e.target.value)}/></div><table><thead><tr><th>排名</th><th>英雄</th><th>层级</th><th>胜率</th><th>登场率</th><th>样本量</th><th/></tr></thead><tbody>{tierRows.map((r,i)=><tr key={r.championId}><td className="subtle">{String(i+1).padStart(2,'0')}</td><td><div className="table-champ"><Portrait champion={champ(r.championId)} size="small"/><b>{champ(r.championId)?.name??r.championId}</b></div></td><td><span className="tier">{r.tier===null?'—':`T${r.tier}`}</span></td><td className={r.winRate>=50?'mint':''}>{fmt(r.winRate,2)}%</td><td>{fmt(r.pickRate,2)}{r.pickRate===null?'':'%'}</td><td>{r.games?.toLocaleString()??'—'}</td><td><button className="text-button" onClick={()=>{setEnemies([r.championId,0,0,0,0]);setOpponentIndex(0);setAuto(false);setTab('draft');}}>寻找 counter ↗</button></td></tr>)}</tbody></table>{!tierRows.length&&<Empty title={loading?'正在获取榜单…':'没有匹配的英雄'} text="榜单仅展示成功获取的真实统计。"/>}</section></>}
 {tab==='team'&&<><div className="summary-grid"><div className="summary-box"><span>可见队友</span><strong>{client.teammates.length}<small> 位</small></strong></div><div className="summary-box"><span>分析范围</span><strong>最近 5<small> 场</small></strong></div><div className="summary-box"><span>数据状态</span><strong className="status-text">{client.connected?'客户端已连接':'等待连接'}</strong></div></div><div className="notice"><span>ⓘ</span> 仅分析当前可识别的队友；匿名玩家显示不可查询。胜率仅针对展示的近期对局。</div>{client.teammates.length===0?<Empty title={client.connected?'当前没有可读取的队友':'连接客户端后，查看队友近况'} text={client.message} action={<button className="primary" onClick={()=>setTab('settings')}>查看连接设置 →</button>}/>:<div className="team-list">{client.teammates.map(p=>{const rating=rateMatches(p.matches);return <section className="panel teammate" key={p.id}><div className="player-heading"><Portrait champion={champ(p.championId)}/><div><h3>{p.name}</h3><span>{p.role||'分路未知'}</span></div><span className={`rating ${rating.label==='上等马'?'good':rating.label==='下等马'?'bad':''}`}>{p.anonymous?'匿名玩家':rating.label}</span><div className="player-stat">近 {rating.count} 场胜率 <b>{fmt(rating.winRate,0)}{rating.winRate!==null?'%':''}</b></div><div className="player-stat">KDA <b>{fmt(rating.kda,2)}</b></div><div className="player-stat">状态分 <b>{rating.score??'—'}</b></div></div>{p.error&&<div className="notice warning">{p.error}</div>}<div className="match-strip">{p.matches.map(m=><div key={m.id} className={`match ${m.win?'win':'loss'}`}><div className="match-result">{m.win?'胜利':'失败'}<small>{new Date(m.date).toLocaleDateString('zh-CN',{month:'numeric',day:'numeric'})}</small></div><div className="table-champ"><Portrait champion={champ(m.championId)} size="small"/><b>{champ(m.championId)?.name??m.championId}</b></div><strong>{m.kills} / {m.deaths} / {m.assists}</strong><span>{m.queueId===420?'单双排':m.queueId===440?'灵活排位':m.queueId===450?'极地大乱斗':`模式 ${m.queueId}`} · {Math.floor(m.duration/60)} 分钟</span></div>)}</div><details><summary>评分依据与样本说明</summary><p>{rating.explanation}</p></details></section>;})}</div>}</>}
 {tab==='settings'&&<div className="settings-grid"><section className="panel"><div className="section-heading"><h2>客户端连接</h2><span className={`pill ${client.connected?'mint':''}`}>{client.connected?'已连接':'未连接'}</span></div><p className="body-copy">打开国服英雄联盟并登录，助手会自动发现本机客户端。若未能发现，可手动选择游戏目录中的 lockfile。</p><div className="setting-row"><span>发现方式</span><b>{lockfile}</b></div><div className="setting-row"><span>当前状态</span><b>{client.message}</b></div><div className="button-row"><button className="primary" onClick={()=>void refreshClient()}>↻ 重新连接</button><button className="outline" onClick={async()=>{try{const p=await api.chooseLockfile();if(p){setLockfile(p);void refreshClient();}}catch(e){setError(String(e));}}}>选择 lockfile</button></div>{error&&<p className="warning">{error}</p>}</section><section className="panel"><h2>数据与边界</h2><div className="info-block"><h3>OP.GG 英雄统计</h3><p>使用公开榜单与对位页面。Global / Emerald+ 统计作为国服选人的参考，界面标明来源版本和缓存时间。</p><button className="text-button" onClick={()=>void api.openSource('https://op.gg/lol/champions')}>访问 OP.GG ↗</button></div><div className="info-block"><h3>本机客户端接口 · LCU</h3><p>只读访问本机客户端。拳头公开 API 没有国服路由；国服战绩接口可用性取决于当前客户端。无法读取时明确提示。</p></div></section><section className="panel"><h2>近期状态怎么计算？</h2><p className="body-copy">近五场胜率权重 70%，KDA 权重 30%。KDA 以总击杀、助攻和死亡计算，达到 5 时该项满分。</p><div className="grade-row"><span className="rating good">上等马</span><b>70 分及以上</b></div><div className="grade-row"><span className="rating">中等马</span><b>40–69 分</b></div><div className="grade-row"><span className="rating bad">下等马</span><b>40 分以下</b></div><p className="subtle">不足三场不评级；不代表长期实力或官方段位。</p></section><section className="panel"><h2>推荐分怎么计算？</h2><p className="body-copy">综合分路胜率、英雄层级和主要对位胜率；对位样本越少，权重越低。敌方多刺客或后排较多时，附加少量可解释的阵容规则分。</p><p className="body-copy">主要对位胜率指候选英雄对阵目标英雄的对局胜率，不等于单杀率，也不是本局获胜保证。</p><div className="notice">推荐分用于比较候选，不是预测胜率。</div></section></div>}
 <footer><span>RIFT COMPANION <span className="slash">/</span> 为每一场认真准备</span><span>{client.updatedAt?`客户端检查 ${new Date(client.updatedAt).toLocaleTimeString('zh-CN')}`:'本机运行 · 只读数据'}</span></footer></div></main></div>;
}
function Empty({title,text,action}:{title:string;text:string;action?:React.ReactNode}){return <div className="empty"><div className="empty-icon">◇</div><h3>{title}</h3><p>{text}</p>{action}</div>;}
function DataState({loading,error,stats,onSource}:{loading:boolean;error:string;stats:StatsSnapshot|null;onSource:()=>unknown}){return <>{loading&&<div className="notice"><span className="spinner"/>正在获取分路榜单与对位统计…</div>}{error&&<div className="notice warning">{error}</div>}{stats&&<div className={`source-line ${stats.stale||stats.error?'warning':''}`}><span>{stats.error??(stats.stale?'正在显示历史缓存':'真实统计 · OP.GG')}{stats.fetchedAt?` · 获取于 ${new Date(stats.fetchedAt).toLocaleString('zh-CN')}`:''} · 非国服统计参考</span><button onClick={()=>void onSource()}>查看来源 ↗</button></div>}</>;}
